apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutcrackerssecurity-blog
  namespace: default
spec:
  selector:
    matchLabels:
      app: nutcrackerssecurity-blog
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nutcrackerssecurity-blog
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: nutcrackerssecurity-blog
        image: "registry-value:latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-credentials-gitlab
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network
                    operator: In
                    values:
                      - servers-untrusted
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: nutcrackerssecurity-blog
