# name: "Build and Deploy"
# on:
#   push:
#     branches:
#       - main
#       - master
#     paths-ignore:
#       - .gitignore
#       - README.md
#       - LICENSE

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           # submodules: true
#           # If using the 'assets' git submodule from Chirpy Starter, uncomment above
#           # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

#       - name: Setup Pages
#         id: pages
#         uses: actions/configure-pages@v4

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.2
#           bundler-cache: true

#       - name: Build site
#         run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
#         env:
#           JEKYLL_ENV: "production"

#     #   - name: Test site
#     #     run: |
#     #       bundle exec htmlproofer _site \
#     #         \-\-disable-external=true \
#     #         \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

#       - name: Upload site artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: "_site${{ steps.pages.outputs.base_path }}"

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4

name: 'Build & Release'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # 3.2.2

        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf  # 1.115.3
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "BASE_URL=$baseurl" >> $GITHUB_ENV
          fi

      - name: Deploy
        run: bash tools/release.sh